#!/bin/bash

sudo npm install pm2@latest -g
sudo npm install medimage -g
cd "$(npm prefix -global)/lib/node_modules/medimage/" 
sudo cp config-original/linORIGINALconfig.json config.json
sudo cp addons/configORIGINAL.json addons/config.json
sudo pm2 start npm --name "medimage-server" -- start ./medimage-server.sh; cd ~
sudo pm2 save
sudo pm2 startup
